### ISSUE TITLE
oracle bug

### ISSUE THREAD

**Issue by liyang1987jay** [PomZWJ/database-export#1]
![image](https://user-images.githubusercontent.com/4651483/65385867-53922480-dd66-11e9-97a3-e26ff91e73e5.png)
![image](https://user-images.githubusercontent.com/4651483/65385872-5d1b8c80-dd66-11e9-8ed2-8bf28f9512fe.png)
我的数据库为32 导出来之后长度都多了4倍

**Comment by PomZWJ** [comment]
因为数据长度取的是oracle的DATA_LENGTH字段，该字段备注是length of the datatype in bytes，提问者的数据类型的数据单位是char(oracle才会出现这个问题)，所以改成了读取CHAR_LENGTH字段,修改的类是在DbExportConstants.getColNameInfoSQL()函数。不过number类型只能在DATA_PRECISION判断了好像，，因为它不属字符，所以CHAR_LENGTH就会为0了，所以如果数据类型如果是number就从DATA_PRECISION取值
