### ISSUE TITLE
有啥建议这边统一提

### ISSUE THREAD

**Issue by PomZWJ** [PomZWJ/database-export#16]

**Comment by awxiaoxian2020** [comment]
是否考虑制作一个生成ER图的

**Comment by huanggenji** [comment]
建议增加docker部署和运行的方式，最好可以提供镜像

**Comment by evachxji** [comment]
现在默认导出库内所有表，如果做成可以选择指定表会更好。 尤其适用于像PDF这种导出后不可随意修改的类型

**Comment by huanggenji** [comment]
做了一个镜像，只是换了一下作者docker file的jdk
镜像地址：docker pull huanggenji/database-export:4.0.0

**Comment by PomZWJ** [comment]
> 做了一个镜像，只是换了一下作者docker file的jdk 镜像地址：docker pull huanggenji/database-export:4.0.0

666

**Comment by nerkeler** [comment]
数据库有将近一千张表，打开和操作 流程都很长，我觉得可以一开始不初始化或者只初始化第一张表的结构，剩下的按需加载，点击表名后再生成文档和结构

**Comment by PomZWJ** [comment]
> 数据库有将近一千张表，打开和操作 流程都很长，我觉得可以一开始不初始化或者只初始化第一张表的结构，剩下的按需加载，点击表名后再生成文档和结构

是预览界面吗?

**Comment by PomZWJ** [comment]
> 现在默认导出库内所有表，如果做成可以选择指定表会更好。 尤其适用于像PDF这种导出后不可随意修改的类型

4.1.0版本已支持

**Comment by PomZWJ** [comment]
> 建议增加docker部署和运行的方式，最好可以提供镜像

最新已经提供docker运行

**Comment by nerkeler** [comment]
> > 数据库有将近一千张表，打开和操作 流程都很长，我觉得可以一开始不初始化或者只初始化第一张表的结构，剩下的按需加载，点击表名后再生成文档和结构
> 
> 是预览界面吗?

是的，我看你现有的逻辑应该是一次性查询返回到前端，点击时触发前端的滚轮到对应位置， 这样表格很多的时候，程序反应很卡顿。

**Comment by PomZWJ** [comment]
> 现在默认导出库内所有表，如果做成可以选择指定表会更好。 尤其适用于像PDF这种导出后不可随意修改的类型

4.1.0版本已支持

**Comment by PomZWJ** [comment]
> 是否考虑制作一个生成ER图的

暂时不考虑，ER图一般跟外键相关，现在外键用得都比较少了，所以生成ER图也没什么意义了

**Comment by kaiser20106** [comment]
论文 mysql转word需要三线表，~~要是能直接设置好三线表样式就好了。~~

**Comment by 1529084525** [comment]
感谢作者，目前已本土化适配，谢谢您的开源。

**Comment by 1529084525** [comment]
提一个小建议：目前导出数据的时候，字段名为空，但是基本上备注即字段名，是否考虑替换二者？

**Comment by PomZWJ** [comment]
> 提一个小建议：目前导出数据的时候，字段名为空，但是基本上备注即字段名，是否考虑替换二者？

字段名还能为空?
